{
 "title": "Main",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Ping Response Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{type=\"ping\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Web Response Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{type=\"https\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "probe_duration_seconds{type=\"http\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSH Response Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{type=\"ssh\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTPS Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{type=\"https\"} == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "HTTP Avg RT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{type=\"http\"})"
    }
   ]
  },
  {
   "title": "HTTP Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{type=\"http\"} == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "HTTPS Avg RT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{type=\"https\"})"
    }
   ]
  },
  {
   "title": "SSH Avg RT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{type=\"ssh\"})"
    }
   ]
  },
  {
   "title": "SSH Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{type=\"ssh\"} == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Ping Avg RT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{type=\"ping\"})"
    }
   ]
  },
  {
   "title": "Ping Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{type=\"ping\"} == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Containers Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(container_last_seen{image!=\"\", instance!=\"mini\"} < time() - 60) + count(container_last_seen{image!=\"\", instance=\"mini\"} < time() - 1500)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Least Free Diskspace",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_free{device=~\"^(/dev/).*\", mountpoint!~\".*(docker).*\",fstype!~\".*(iso).*\"}/node_filesystem_size)"
    }
   ]
  },
  {
   "title": "VPN Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(openvpn_connected_clients)" }
   ]
  },
  {
   "title": "VPNs Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(openvpn_last_updated < time() - 120) OR vector(0)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - node_memory_MemFree_bytes{instance=\"vps1\"}/node_memory_MemTotal_bytes{instance=\"vps1\"} * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - node_memory_MemFree_bytes{instance=\"vps4\"}/node_memory_MemTotal_bytes{instance=\"vps4\"} * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - node_memory_MemFree_bytes{instance=\"vps5\"}/node_memory_MemTotal_bytes{instance=\"vps5\"} * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - node_memory_MemFree_bytes{instance=\"vps10\"}/node_memory_MemTotal_bytes{instance=\"vps10\"} * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - node_memory_MemFree_bytes{instance=\"home\"}/node_memory_MemTotal_bytes{instance=\"home\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - 100*(sum by(instance)(irate(node_cpu_seconds_total{mode='idle', instance='vps1'}[5m]))/8)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - 100*(sum by(instance)(irate(node_cpu_seconds_total{mode='idle', instance='vps4'}[5m]))/8)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - 100*(sum by(instance)(irate(node_cpu_seconds_total{mode='idle', instance='vps5'}[5m]))/8)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - 100*(sum by(instance)(irate(node_cpu_seconds_total{mode='idle', instance='vps10'}[5m]))/8)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - 100*(sum by(instance)(irate(node_cpu_seconds_total{mode='idle', instance='home'}[5m]))/8)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}